spring:
  application:
    name: mongo-kotlin-acid
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/bank?authSource=admin

vendor:
  timeout-ms: 200

# Настройки внешнего сервиса подписок (WireMock)
external:
  subscription:
    service:
      url: http://localhost:8090

logging:
  level:
    org.mongodb.driver: WARN
    io.netty: WARN
    com.mongodb: WARN

# Настройка кодов ошибок для стратегий
error:
  strategies:
    badRequest: 400
    forbidden: 403
    notFound: 404
    conflict: 409
    internalServerError: 500

# Cloud Messages - Сообщения об ошибках
error.subscription.fetch.invalid.request: "При получении подписок для пользователя с customerId: {customerId}, были введены некорректные данные."
error.subscription.fetch.forbidden: "Пользователь с customerId: {customerId}, не может получить подписки."
error.subscription.fetch.customer.not.found: "Пользователь с customerId: {customerId}, не найден во внешнем сервисе подписок."
error.subscription.fetch.temporarily.unavailable: "Получение подписок для пользователя с customerId: {customerId}, временно недоступно."
error.subscription.fetch.external.service.error: "Получение подписок для пользователя с customerId: {customerId}, невозможно, так как внешний сервис недоступен."
error.subscription.fetch.unknown.error: "Получение подписок для пользователя с customerId: {customerId}, невозможно из-за неизвестной ошибки внешнего сервиса."
error.subscription.fetch.offer.not.found: "Предложение о покупке подписки по offerId: {offerId}, не найдено для пользователя с customerId: {customerId}."
error.subscription.fetch.adapter.not.available: "Покупка подписки по offerId: {offerId}, невозможна, так как payment adapter по publicGatewayId: {publicGatewayId}, не доступен для пользователя с customerId: {customerId}."
error.auth.missing.user.id.header: "Отсутствует идентификатор пользователя для получения подписок."
error.unexpected: "Непредвиденная ошибка при получении подписок для пользователя с customerId: {customerId}."