spring:
  application:
    name: mongo-kotlin-acid
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/bank?authSource=admin

vendor:
  timeout-ms: 200

logging:
  level:
    org.mongodb.driver: WARN
    io.netty: WARN
    com.mongodb: WARN